import type { WastageReport } from "@/types/wastage-reporting";

export const wrMockData: WastageReport[] = [
  {
    id: "wr-001",
    wr_no: "WR-2602-0001",
    date: "2026-02-20",
    location_id: "loc_004",
    location_name: "ห้องเย็น",
    items: [
      {
        id: "wri-001",
        product_id: "prod-18",
        product_name: "เนื้อสันใน",
        product_code: "MT-001",
        qty: 3,
        unit_id: "unit-kg",
        unit_name: "kg",
        unit_cost: 850,
        loss_value: 2550,
      },
      {
        id: "wri-002",
        product_id: "prod-24",
        product_name: "ปลาแซลมอน",
        product_code: "SF-003",
        qty: 2,
        unit_id: "unit-kg",
        unit_name: "kg",
        unit_cost: 850,
        loss_value: 1700,
      },
    ],
    qty_sum: 5,
    loss_value: 4250,
    reason: "ตู้เย็นขัดข้องข้ามคืน อุณหภูมิสูงเกินกำหนด",
    reportor_id: "user-03",
    reportor_name: "สมชาย วงศ์ดี",
    status: "approved",
    attachments: [
      {
        id: "att-001",
        name: "ภาพถ่ายตู้เย็น.jpg",
        url: "https://example.com/att/wr001-1.jpg",
      },
      {
        id: "att-002",
        name: "ใบบันทึกอุณหภูมิ.pdf",
        url: "https://example.com/att/wr001-2.pdf",
      },
    ],
    created_at: "2026-02-20T08:30:00Z",
    updated_at: "2026-02-20T10:15:00Z",
  },
  {
    id: "wr-002",
    wr_no: "WR-2602-0002",
    date: "2026-02-21",
    location_id: "loc_002",
    location_name: "บาร์เครื่องดื่ม",
    items: [
      {
        id: "wri-003",
        product_id: "prod-07",
        product_name: "เบียร์สิงห์",
        product_code: "BV-001",
        qty: 6,
        unit_id: "unit-bottle",
        unit_name: "ขวด",
        unit_cost: 80,
        loss_value: 480,
      },
    ],
    qty_sum: 6,
    loss_value: 480,
    reason: "ขวดแตกระหว่างขนย้าย",
    reportor_id: "user-05",
    reportor_name: "วิภา แสงทอง",
    status: "approved",
    attachments: [
      {
        id: "att-003",
        name: "ภาพขวดแตก.jpg",
        url: "https://example.com/att/wr002-1.jpg",
      },
    ],
    created_at: "2026-02-21T09:00:00Z",
    updated_at: "2026-02-21T11:30:00Z",
  },
  {
    id: "wr-003",
    wr_no: "WR-2602-0003",
    date: "2026-02-22",
    location_id: "loc_001",
    location_name: "ครัวหลัก",
    items: [
      {
        id: "wri-004",
        product_id: "prod-04",
        product_name: "ซอสหอยนางรม",
        product_code: "SC-002",
        qty: 3,
        unit_id: "unit-bottle",
        unit_name: "ขวด",
        unit_cost: 120,
        loss_value: 360,
      },
      {
        id: "wri-005",
        product_id: "prod-03",
        product_name: "น้ำปลา",
        product_code: "SC-001",
        qty: 2,
        unit_id: "unit-bottle",
        unit_name: "ขวด",
        unit_cost: 85,
        loss_value: 170,
      },
      {
        id: "wri-006",
        product_id: "prod-01",
        product_name: "น้ำมันพืช",
        product_code: "OL-001",
        qty: 3,
        unit_id: "unit-liter",
        unit_name: "ลิตร",
        unit_cost: 130,
        loss_value: 390,
      },
    ],
    qty_sum: 8,
    loss_value: 920,
    reason: "ชั้นวางพังทลาย ของหล่นแตกเสียหาย",
    reportor_id: "user-02",
    reportor_name: "อรุณ ศรีสุข",
    status: "pending",
    attachments: [
      {
        id: "att-004",
        name: "ภาพชั้นวางเสียหาย.jpg",
        url: "https://example.com/att/wr003-1.jpg",
      },
      {
        id: "att-005",
        name: "รายการสินค้าเสียหาย.xlsx",
        url: "https://example.com/att/wr003-2.xlsx",
      },
    ],
    created_at: "2026-02-22T07:45:00Z",
    updated_at: "2026-02-22T07:45:00Z",
  },
  {
    id: "wr-004",
    wr_no: "WR-2602-0004",
    date: "2026-02-22",
    location_id: "loc_004",
    location_name: "ห้องเย็น",
    items: [
      {
        id: "wri-007",
        product_id: "prod-21",
        product_name: "นมสด",
        product_code: "DY-001",
        qty: 8,
        unit_id: "unit-liter",
        unit_name: "ลิตร",
        unit_cost: 120,
        loss_value: 960,
      },
      {
        id: "wri-008",
        product_id: "prod-23",
        product_name: "ครีมสด",
        product_code: "DY-003",
        qty: 4,
        unit_id: "unit-liter",
        unit_name: "ลิตร",
        unit_cost: 150,
        loss_value: 600,
      },
    ],
    qty_sum: 12,
    loss_value: 1560,
    reason: "หมดอายุ ไม่ได้หมุนเวียนสต็อก FIFO",
    reportor_id: "user-03",
    reportor_name: "สมชาย วงศ์ดี",
    status: "rejected",
    attachments: [],
    created_at: "2026-02-22T14:00:00Z",
    updated_at: "2026-02-22T16:30:00Z",
  },
  {
    id: "wr-005",
    wr_no: "WR-2602-0005",
    date: "2026-02-23",
    location_id: "loc_005",
    location_name: "แผนกแม่บ้าน",
    items: [
      {
        id: "wri-009",
        product_id: "prod-27",
        product_name: "ผ้าขนหนูตัวใหญ่",
        product_code: "HK-003",
        qty: 10,
        unit_id: "unit-pcs",
        unit_name: "ผืน",
        unit_cost: 350,
        loss_value: 3500,
      },
    ],
    qty_sum: 10,
    loss_value: 3500,
    reason: "เปื้อนสารเคมีจากน้ำยาทำความสะอาดรั่ว ซักไม่ออก",
    reportor_id: "user-07",
    reportor_name: "นภา พรหมมา",
    status: "pending",
    attachments: [
      {
        id: "att-006",
        name: "ภาพผ้าเสียหาย.jpg",
        url: "https://example.com/att/wr005-1.jpg",
      },
    ],
    created_at: "2026-02-23T10:00:00Z",
    updated_at: "2026-02-23T10:00:00Z",
  },
];
