import { createBrowserRouter, Navigate } from "react-router";
import { RequireAuth } from "@/components/auth/require-auth";
import AppRoot from "./app-root";
import RootLayout from "./root-layout";
import { RouteErrorBoundaryAdapter } from "./module-error-boundary-adapter";
import { RootErrorBoundary } from "./root-error-boundary";

const ProtectedShell = () => (
  <RequireAuth>
    <RootLayout />
  </RequireAuth>
);

export const router = createBrowserRouter([
  {
    Component: AppRoot,
    ErrorBoundary: RootErrorBoundary,
    children: [
      { path: "/login", lazy: () => import("./login/page") },
      // Public price-list route — vendor ภายนอกเปิดจากลิงก์ในอีเมล (ไม่ต้อง auth)
      { path: "/pl/:url_token", lazy: () => import("./external/pl/price-list-external.route") },
      {
        Component: ProtectedShell,
        children: [
          { index: true, element: <Navigate to="/dashboard" replace /> },
          {
            path: "dashboard",
            lazy: () => import("./dashboard/dashboard.route"),
            ErrorBoundary: RouteErrorBoundaryAdapter,
          },
          {
            path: "profile",
            lazy: () => import("./profile/profile.route"),
            ErrorBoundary: RouteErrorBoundaryAdapter,
          },
          {
            path: "profile/setting",
            lazy: () => import("./profile/profile-setting.route"),
            ErrorBoundary: RouteErrorBoundaryAdapter,
          },
          {
            path: "notifications",
            lazy: () => import("./notifications/page"),
            ErrorBoundary: RouteErrorBoundaryAdapter,
          },
          {
            path: "config",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./config/config.route") },
              { path: "unit", lazy: () => import("./config/unit/unit.route") },
              { path: "currency", lazy: () => import("./config/currency/currency.route") },
              { path: "adjustment-type", lazy: () => import("./config/adjustment-type/adjustment-type.route") },
              { path: "business-type", lazy: () => import("./config/business-type/business-type.route") },
              { path: "certification", lazy: () => import("./config/certification/certification.route") },
              { path: "credit-note-reason", lazy: () => import("./config/credit-note-reason/credit-note-reason.route") },
              { path: "credit-term", lazy: () => import("./config/credit-term/credit-term.route") },
              { path: "delivery-point", lazy: () => import("./config/delivery-point/delivery-point.route") },
              { path: "eco", lazy: () => import("./config/eco/eco.route") },
              { path: "exchange-rate", lazy: () => import("./config/exchange-rate/exchange-rate.route") },
              { path: "extra-cost", lazy: () => import("./config/extra-cost/extra-cost.route") },
              { path: "tax-profile", lazy: () => import("./config/tax-profile/tax-profile.route") },
              { path: "department", lazy: () => import("./config/department/department.route") },
              { path: "department/new", lazy: () => import("./config/department/department-new.route") },
              { path: "department/:id", lazy: () => import("./config/department/department-edit.route") },
              { path: "location", lazy: () => import("./config/location/location.route") },
              { path: "location/new", lazy: () => import("./config/location/location-new.route") },
              { path: "location/:id", lazy: () => import("./config/location/location-edit.route") },
            ],
          },
          {
            path: "procurement",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./procurement/procurement.route") },
              { path: "purchase-request-template", lazy: () => import("./procurement/purchase-request-template/purchase-request-template.route") },
              { path: "purchase-request-template/new", lazy: () => import("./procurement/purchase-request-template/purchase-request-template-new.route") },
              { path: "purchase-request-template/:id", lazy: () => import("./procurement/purchase-request-template/purchase-request-template-edit.route") },
              { path: "credit-note", lazy: () => import("./procurement/credit-note/credit-note.route") },
              { path: "credit-note/new", lazy: () => import("./procurement/credit-note/credit-note-new.route") },
              { path: "credit-note/:id", lazy: () => import("./procurement/credit-note/credit-note-edit.route") },
              { path: "goods-receive-note", lazy: () => import("./procurement/goods-receive-note/goods-receive-note.route") },
              { path: "goods-receive-note/new", lazy: () => import("./procurement/goods-receive-note/goods-receive-note-new.route") },
              { path: "goods-receive-note/:id", lazy: () => import("./procurement/goods-receive-note/goods-receive-note-edit.route") },
              { path: "purchase-order", lazy: () => import("./procurement/purchase-order/purchase-order.route") },
              { path: "purchase-order/new", lazy: () => import("./procurement/purchase-order/purchase-order-new.route") },
              { path: "purchase-order/from-price-list", lazy: () => import("./procurement/purchase-order/from-price-list/from-price-list.route") },
              { path: "purchase-order/:id", lazy: () => import("./procurement/purchase-order/purchase-order-edit.route") },
              { path: "purchase-request", lazy: () => import("./procurement/purchase-request/purchase-request.route") },
              { path: "purchase-request/new", lazy: () => import("./procurement/purchase-request/purchase-request-new.route") },
              { path: "purchase-request/:id", lazy: () => import("./procurement/purchase-request/purchase-request-edit.route") },
              { path: "approval", lazy: () => import("./procurement/approval/approval.route") },
            ],
          },
          {
            path: "inventory-management",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./inventory-management/inventory-management.route") },
              { path: "inventory-adjustment", lazy: () => import("./inventory-management/inventory-adjustment/inventory-adjustment.route") },
              { path: "inventory-adjustment/new", lazy: () => import("./inventory-management/inventory-adjustment/inventory-adjustment-new.route") },
              { path: "inventory-adjustment/:id", lazy: () => import("./inventory-management/inventory-adjustment/inventory-adjustment-edit.route") },
              { path: "transaction", lazy: () => import("./inventory-management/transaction/transaction.route") },
              { path: "physical-count", lazy: () => import("./inventory-management/physical-count/physical-count.route") },
              { path: "physical-count/new", lazy: () => import("./inventory-management/physical-count/physical-count-new.route") },
              { path: "physical-count/:id", lazy: () => import("./inventory-management/physical-count/physical-count-edit.route") },
              { path: "physical-count/:id/entry", lazy: () => import("./inventory-management/physical-count/physical-count-entry.route") },
              { path: "physical-count/:id/review", lazy: () => import("./inventory-management/physical-count/physical-count-review.route") },
              { path: "spot-check", lazy: () => import("./inventory-management/spot-check/page") },
              { path: "spot-check/location/:location_id", lazy: () => import("./inventory-management/spot-check/location/[location_id]/page") },
              { path: "spot-check/:id", lazy: () => import("./inventory-management/spot-check/[id]/page") },
              { path: "spot-check/:id/review", lazy: () => import("./inventory-management/spot-check/[id]/review/page") },
              { path: "period-end", lazy: () => import("./inventory-management/period-end/page") },
              { path: "period-end/review", lazy: () => import("./inventory-management/period-end/review/page") },
            ],
          },
          {
            path: "vendor-management",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./vendor-management/page") },
              { path: "vendor", lazy: () => import("./vendor-management/vendor/page") },
              { path: "vendor/new", lazy: () => import("./vendor-management/vendor/new/page") },
              { path: "vendor/:id", lazy: () => import("./vendor-management/vendor/[id]/page") },
              { path: "price-list", lazy: () => import("./vendor-management/price-list/page") },
              { path: "price-list/new", lazy: () => import("./vendor-management/price-list/new/page") },
              { path: "price-list/:id", lazy: () => import("./vendor-management/price-list/[id]/page") },
              { path: "price-list-template", lazy: () => import("./vendor-management/price-list-template/page") },
              { path: "price-list-template/new", lazy: () => import("./vendor-management/price-list-template/new/page") },
              { path: "price-list-template/:id", lazy: () => import("./vendor-management/price-list-template/[id]/page") },
              { path: "request-price-list", lazy: () => import("./vendor-management/request-price-list/page") },
              { path: "request-price-list/new", lazy: () => import("./vendor-management/request-price-list/new/page") },
              { path: "request-price-list/:id", lazy: () => import("./vendor-management/request-price-list/[id]/page") },
            ],
          },
          {
            path: "store-operation",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./store-operation/page") },
              { path: "store-requisition", lazy: () => import("./store-operation/store-requisition/page") },
              { path: "store-requisition/new", lazy: () => import("./store-operation/store-requisition/new/page") },
              { path: "store-requisition/:id", lazy: () => import("./store-operation/store-requisition/[id]/page") },
              { path: "wastage-reporting", lazy: () => import("./store-operation/wastage-reporting/page") },
              { path: "wastage-reporting/new", lazy: () => import("./store-operation/wastage-reporting/new/page") },
              { path: "wastage-reporting/:id", lazy: () => import("./store-operation/wastage-reporting/[id]/page") },
              { path: "stock-replenishment", lazy: () => import("./store-operation/stock-replenishment/page") },
            ],
          },
          {
            path: "operation-plan",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./operation-plan/page") },
              { path: "category", lazy: () => import("./operation-plan/category/page") },
              { path: "category/new", lazy: () => import("./operation-plan/category/new/page") },
              { path: "category/:id", lazy: () => import("./operation-plan/category/[id]/page") },
              { path: "cuisine", lazy: () => import("./operation-plan/cuisine/page") },
              { path: "cuisine/new", lazy: () => import("./operation-plan/cuisine/new/page") },
              { path: "cuisine/:id", lazy: () => import("./operation-plan/cuisine/[id]/page") },
              { path: "recipe", lazy: () => import("./operation-plan/recipe/page") },
              { path: "recipe/new", lazy: () => import("./operation-plan/recipe/new/page") },
              { path: "recipe/:id", lazy: () => import("./operation-plan/recipe/[id]/page") },
              { path: "equipment", lazy: () => import("./operation-plan/equipment/page") },
              { path: "equipment/new", lazy: () => import("./operation-plan/equipment/new/page") },
              { path: "equipment/:id", lazy: () => import("./operation-plan/equipment/[id]/page") },
              { path: "recipe-equipment-category", lazy: () => import("./operation-plan/recipe-equipment-category/page") },
              { path: "equipment-category", lazy: () => import("./operation-plan/equipment-category/page") },
            ],
          },
          {
            path: "product-management",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./product-management/page") },
              { path: "category", lazy: () => import("./product-management/category/page") },
              { path: "product", lazy: () => import("./product-management/product/page") },
              { path: "product/new", lazy: () => import("./product-management/product/new/page") },
              { path: "product/:id", lazy: () => import("./product-management/product/[id]/page") },
            ],
          },
          {
            path: "system-admin",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./system-admin/page") },
              { path: "role", lazy: () => import("./system-admin/role/page") },
              { path: "role/new", lazy: () => import("./system-admin/role/new/page") },
              { path: "role/:id", lazy: () => import("./system-admin/role/[id]/page") },
              { path: "notification-template", lazy: () => import("./system-admin/notification-template/page") },
              { path: "notification-template/new", lazy: () => import("./system-admin/notification-template/new/page") },
              { path: "notification-template/:id", lazy: () => import("./system-admin/notification-template/[id]/page") },
              { path: "period", lazy: () => import("./system-admin/period/page") },
              { path: "user-activity", lazy: () => import("./system-admin/user-activity/page") },
              { path: "user", lazy: () => import("./system-admin/user/page") },
              { path: "user/:id", lazy: () => import("./system-admin/user/[id]/page") },
              { path: "document", lazy: () => import("./system-admin/document/page") },
              { path: "query-dataset", lazy: () => import("./system-admin/query-dataset/page") },
              { path: "activity-log", lazy: () => import("./system-admin/activity-log/page") },
              { path: "workflow", lazy: () => import("./system-admin/workflow/page") },
              { path: "workflow/new", lazy: () => import("./system-admin/workflow/new/page") },
              { path: "workflow/:id", lazy: () => import("./system-admin/workflow/[id]/page") },
              { path: "running-code", lazy: () => import("./system-admin/running-code/page") },
              { path: "config-email", lazy: () => import("./system-admin/config-email/page") },
              { path: "dashboard-dataset", lazy: () => import("./system-admin/dashboard-dataset/page") },
            ],
          },
          {
            path: "report",
            ErrorBoundary: RouteErrorBoundaryAdapter,
            children: [
              { index: true, lazy: () => import("./report/report.route") },
              { path: "list", lazy: () => import("./report/list/report-list.route") },
              { path: "schedules", lazy: () => import("./report/schedules/report-schedules.route") },
              { path: "history", lazy: () => import("./report/history/report-history.route") },
            ],
          },
        ],
      },
      { path: "*", lazy: () => import("./not-found/page") },
    ],
  },
]);
