import type { Locations } from "@/types/stock-replenishment";

export const mockData: Locations = [
  {
    location_id: "loc_001",
    location_name: "ครัวหลัก",
    products_location: [
      {
        id: "1",
        name: "น้ำมันพืช (ลิตร)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_01", name: "น้ำมัน/ไขมัน" },
        item_group: { id: "ig_01", name: "น้ำมันพืช" },
        current: 2,
        par_level: 20,
        need: 18,
        status: "critical",
      },
      {
        id: "2",
        name: "ข้าวหอมมะลิ (กก.)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_02", name: "ข้าว/แป้ง" },
        item_group: { id: "ig_02", name: "ข้าวสาร" },
        current: 15,
        par_level: 50,
        need: 35,
        status: "critical",
      },
      {
        id: "3",
        name: "น้ำปลา (ขวด)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_03", name: "เครื่องปรุงรส" },
        item_group: { id: "ig_03", name: "ซอส/น้ำปลา" },
        current: 8,
        par_level: 12,
        need: 4,
        status: "warning",
      },
      {
        id: "4",
        name: "ซอสหอยนางรม (ขวด)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_03", name: "เครื่องปรุงรส" },
        item_group: { id: "ig_03", name: "ซอส/น้ำปลา" },
        current: 5,
        par_level: 10,
        need: 5,
        status: "warning",
      },
      {
        id: "5",
        name: "กระเทียม (กก.)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_04", name: "ผักสด" },
        item_group: { id: "ig_04", name: "เครื่องเทศสด" },
        current: 1,
        par_level: 8,
        need: 7,
        status: "critical",
      },
      {
        id: "6",
        name: "พริกไทยดำ (กก.)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_05", name: "เครื่องเทศแห้ง" },
        item_group: { id: "ig_05", name: "พริกไทย" },
        current: 3,
        par_level: 5,
        need: 2,
        status: "low",
      },
    ],
  },
  {
    location_id: "loc_002",
    location_name: "บาร์เครื่องดื่ม",
    products_location: [
      {
        id: "7",
        name: "เบียร์สิงห์ (ขวด)",
        category: { id: "cat_02", name: "เครื่องดื่ม" },
        sub_category: { id: "sub_06", name: "เบียร์" },
        item_group: { id: "ig_06", name: "เบียร์ไทย" },
        current: 24,
        par_level: 100,
        need: 76,
        status: "critical",
      },
      {
        id: "8",
        name: "โซดา (แพ็ค)",
        category: { id: "cat_02", name: "เครื่องดื่ม" },
        sub_category: { id: "sub_07", name: "น้ำอัดลม" },
        item_group: { id: "ig_07", name: "โซดา/น้ำอัดลม" },
        current: 8,
        par_level: 15,
        need: 7,
        status: "warning",
      },
      {
        id: "9",
        name: "มะนาว (ลูก)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_08", name: "ผลไม้สด" },
        item_group: { id: "ig_08", name: "ผลไม้สำหรับเครื่องดื่ม" },
        current: 30,
        par_level: 80,
        need: 50,
        status: "critical",
      },
      {
        id: "10",
        name: "น้ำเชื่อม (ขวด)",
        category: { id: "cat_02", name: "เครื่องดื่ม" },
        sub_category: { id: "sub_09", name: "ไซรัป" },
        item_group: { id: "ig_09", name: "น้ำเชื่อม/ไซรัป" },
        current: 4,
        par_level: 6,
        need: 2,
        status: "low",
      },
      {
        id: "11",
        name: "น้ำแข็ง (ถุง)",
        category: { id: "cat_02", name: "เครื่องดื่ม" },
        sub_category: { id: "sub_10", name: "น้ำแข็ง" },
        item_group: { id: "ig_10", name: "น้ำแข็งก้อน" },
        current: 3,
        par_level: 20,
        need: 17,
        status: "critical",
      },
    ],
  },
  {
    location_id: "loc_003",
    location_name: "ห้องเก็บของแห้ง",
    products_location: [
      {
        id: "12",
        name: "แป้งสาลี (กก.)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_02", name: "ข้าว/แป้ง" },
        item_group: { id: "ig_11", name: "แป้ง" },
        current: 10,
        par_level: 25,
        need: 15,
        status: "warning",
      },
      {
        id: "13",
        name: "น้ำตาลทราย (กก.)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_03", name: "เครื่องปรุงรส" },
        item_group: { id: "ig_12", name: "น้ำตาล" },
        current: 18,
        par_level: 20,
        need: 2,
        status: "low",
      },
      {
        id: "14",
        name: "เส้นสปาเก็ตตี้ (แพ็ค)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_02", name: "ข้าว/แป้ง" },
        item_group: { id: "ig_13", name: "เส้นพาสต้า" },
        current: 6,
        par_level: 30,
        need: 24,
        status: "critical",
      },
      {
        id: "15",
        name: "ซอสมะเขือเทศ (กระป๋อง)",
        category: { id: "cat_01", name: "วัตถุดิบ" },
        sub_category: { id: "sub_03", name: "เครื่องปรุงรส" },
        item_group: { id: "ig_03", name: "ซอส/น้ำปลา" },
        current: 12,
        par_level: 20,
        need: 8,
        status: "warning",
      },
      {
        id: "16",
        name: "ทูน่ากระป๋อง",
        category: { id: "cat_03", name: "อาหารกระป๋อง" },
        sub_category: { id: "sub_11", name: "ปลากระป๋อง" },
        item_group: { id: "ig_14", name: "ทูน่า" },
        current: 20,
        par_level: 24,
        need: 4,
        status: "low",
      },
      {
        id: "17",
        name: "นมข้นหวาน (กระป๋อง)",
        category: { id: "cat_03", name: "อาหารกระป๋อง" },
        sub_category: { id: "sub_12", name: "นมกระป๋อง" },
        item_group: { id: "ig_15", name: "นมข้น" },
        current: 5,
        par_level: 15,
        need: 10,
        status: "warning",
      },
    ],
  },
  {
    location_id: "loc_004",
    location_name: "ห้องเย็น",
    products_location: [
      {
        id: "18",
        name: "เนื้อสันใน (กก.)",
        category: { id: "cat_04", name: "เนื้อสัตว์" },
        sub_category: { id: "sub_13", name: "เนื้อวัว" },
        item_group: { id: "ig_16", name: "เนื้อสัน" },
        current: 2,
        par_level: 15,
        need: 13,
        status: "critical",
      },
      {
        id: "19",
        name: "อกไก่ (กก.)",
        category: { id: "cat_04", name: "เนื้อสัตว์" },
        sub_category: { id: "sub_14", name: "เนื้อไก่" },
        item_group: { id: "ig_17", name: "อกไก่" },
        current: 5,
        par_level: 20,
        need: 15,
        status: "critical",
      },
      {
        id: "20",
        name: "กุ้งขาว (กก.)",
        category: { id: "cat_05", name: "อาหารทะเล" },
        sub_category: { id: "sub_15", name: "กุ้ง" },
        item_group: { id: "ig_18", name: "กุ้งสด" },
        current: 3,
        par_level: 10,
        need: 7,
        status: "critical",
      },
      {
        id: "21",
        name: "นมสด (ลิตร)",
        category: { id: "cat_06", name: "ผลิตภัณฑ์นม" },
        sub_category: { id: "sub_16", name: "นมสด" },
        item_group: { id: "ig_19", name: "นมพาสเจอร์ไรส์" },
        current: 8,
        par_level: 12,
        need: 4,
        status: "warning",
      },
      {
        id: "22",
        name: "เนย (กก.)",
        category: { id: "cat_06", name: "ผลิตภัณฑ์นม" },
        sub_category: { id: "sub_17", name: "เนย/ครีม" },
        item_group: { id: "ig_20", name: "เนย" },
        current: 4,
        par_level: 5,
        need: 1,
        status: "low",
      },
      {
        id: "23",
        name: "ครีมสด (ลิตร)",
        category: { id: "cat_06", name: "ผลิตภัณฑ์นม" },
        sub_category: { id: "sub_17", name: "เนย/ครีม" },
        item_group: { id: "ig_21", name: "ครีมสด" },
        current: 1,
        par_level: 6,
        need: 5,
        status: "critical",
      },
      {
        id: "24",
        name: "ปลาแซลมอน (กก.)",
        category: { id: "cat_05", name: "อาหารทะเล" },
        sub_category: { id: "sub_18", name: "ปลา" },
        item_group: { id: "ig_22", name: "ปลานำเข้า" },
        current: 2,
        par_level: 8,
        need: 6,
        status: "critical",
      },
    ],
  },
  {
    location_id: "loc_005",
    location_name: "แผนกแม่บ้าน",
    products_location: [
      {
        id: "25",
        name: "สบู่ก้อน (ชิ้น)",
        category: { id: "cat_07", name: "ของใช้" },
        sub_category: { id: "sub_19", name: "สบู่/แชมพู" },
        item_group: { id: "ig_23", name: "สบู่" },
        current: 50,
        par_level: 200,
        need: 150,
        status: "critical",
      },
      {
        id: "26",
        name: "แชมพู (ขวด)",
        category: { id: "cat_07", name: "ของใช้" },
        sub_category: { id: "sub_19", name: "สบู่/แชมพู" },
        item_group: { id: "ig_24", name: "แชมพู" },
        current: 80,
        par_level: 200,
        need: 120,
        status: "critical",
      },
      {
        id: "27",
        name: "ผ้าขนหนูตัวใหญ่",
        category: { id: "cat_07", name: "ของใช้" },
        sub_category: { id: "sub_20", name: "ผ้า/ผ้าเช็ดตัว" },
        item_group: { id: "ig_25", name: "ผ้าขนหนู" },
        current: 45,
        par_level: 60,
        need: 15,
        status: "warning",
      },
      {
        id: "28",
        name: "น้ำยาทำความสะอาด (แกลลอน)",
        category: { id: "cat_08", name: "ทำความสะอาด" },
        sub_category: { id: "sub_21", name: "น้ำยาทำความสะอาด" },
        item_group: { id: "ig_26", name: "น้ำยาอเนกประสงค์" },
        current: 6,
        par_level: 10,
        need: 4,
        status: "warning",
      },
      {
        id: "29",
        name: "กระดาษทิชชู่ (ม้วน)",
        category: { id: "cat_07", name: "ของใช้" },
        sub_category: { id: "sub_22", name: "กระดาษ" },
        item_group: { id: "ig_27", name: "กระดาษทิชชู่" },
        current: 100,
        par_level: 300,
        need: 200,
        status: "critical",
      },
      {
        id: "30",
        name: "ถุงขยะ (แพ็ค)",
        category: { id: "cat_08", name: "ทำความสะอาด" },
        sub_category: { id: "sub_23", name: "ถุง/บรรจุภัณฑ์" },
        item_group: { id: "ig_28", name: "ถุงขยะ" },
        current: 15,
        par_level: 20,
        need: 5,
        status: "low",
      },
    ],
  },
];
