import type { AccountMappingRow } from "@/types/account-mapping";

/**
 * ข้อมูลตัวอย่างระหว่างรอ backend — หน้า list อ่านจากตัวนี้ตรง ๆ ไม่ยิง API
 *
 * ตั้งใจให้มีทั้งแถวที่ผูกแล้วและยังไม่ผูก ทั้ง AP และ GL และมีแถวที่
 * `last_scanned_at` เป็น null เพื่อให้เห็นทุกสภาพของตารางจริงตั้งแต่ยังไม่มี API
 * **ลบไฟล์นี้ทิ้งเมื่อ endpoint พร้อม**
 */
export const AM_MOCK_ROWS: AccountMappingRow[] = [
  {
    id: "map_0001",
    business_unit: "VALHALLA",
    store_location: { code: "1MK01", name: "Hall of the Eternal Feast" },
    category: { code: "1", name: "Food" },
    sub_category: { code: "10", name: "Meat" },
    item_group: { code: "1001", name: "Sæhrímnir - The Beast Reborn Nightly" },
    department: { code: "GEN", name: "Non Operating" },
    account_code: {
      code: "1106002",
      name: "INVENTORY - FLESH OF THE ENDLESS BANQUET",
    },
    is_mapped: true,
    mapping_type: "AP",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0002",
    business_unit: "VALHALLA",
    store_location: { code: "1MK01", name: "Hall of the Eternal Feast" },
    category: { code: "1", name: "Food" },
    sub_category: { code: "10", name: "Meat" },
    item_group: { code: "1006", name: "Cured Offering of the Cold Season" },
    department: { code: "GEN", name: "Non Operating" },
    account_code: {
      code: "1106002",
      name: "INVENTORY - FLESH OF THE ENDLESS BANQUET",
    },
    is_mapped: true,
    mapping_type: "AP",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0003",
    business_unit: "OLYMPUS",
    store_location: { code: "2AG02", name: "Cellar of Ambrosia" },
    category: { code: "2", name: "Beverage" },
    sub_category: { code: "24", name: "Wine" },
    item_group: { code: "2403", name: "Sparkling - Tears of the Thunder God" },
    department: { code: "DIO", name: "Rites & Revelry" },
    account_code: {
      code: "1107001",
      name: "INVENTORY - NECTAR VAULT (IMMORTAL GRADE)",
    },
    is_mapped: true,
    mapping_type: "AP",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0004",
    business_unit: "OLYMPUS",
    store_location: { code: "2AG02", name: "Cellar of Ambrosia" },
    category: { code: "2", name: "Beverage" },
    sub_category: { code: "25", name: "Spirits" },
    item_group: { code: "2511", name: "Aged 40 Winters in Oaken Sarcophagus" },
    department: { code: "DIO", name: "Rites & Revelry" },
    account_code: { code: "1107002", name: "INVENTORY - LIQUID FIRE RESERVE" },
    is_mapped: true,
    mapping_type: "AP",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0005",
    business_unit: "THEBES",
    store_location: { code: "3DS01", name: "Chamber of Dry Provisions" },
    category: { code: "1", name: "Food" },
    sub_category: { code: "13", name: "Grain & Flour" },
    item_group: { code: "1302", name: "Grain of the Seven Fat Years" },
    department: { code: "GEN", name: "Non Operating" },
    account_code: {
      code: "1106009",
      name: "INVENTORY - GRANARY OF THE PROPHECY",
    },
    is_mapped: true,
    mapping_type: "AP",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0006",
    business_unit: "THEBES",
    store_location: { code: "3DS01", name: "Chamber of Dry Provisions" },
    category: { code: "1", name: "Food" },
    sub_category: { code: "16", name: "Oil & Vinegar" },
    item_group: {
      code: "1601",
      name: "Anointing Oil - Pressed Under Moonlight",
    },
    department: { code: "GEN", name: "Non Operating" },
    account_code: { code: "1106011", name: "INVENTORY - SACRED UNGUENTS" },
    is_mapped: false,
    mapping_type: "AP",
    last_scanned_at: null,
  },
  {
    id: "map_0007",
    business_unit: "BABYLON",
    store_location: { code: "4HK01", name: "Hanging Terrace Housekeeping" },
    category: { code: "3", name: "Supplies" },
    sub_category: { code: "31", name: "Linen" },
    item_group: {
      code: "3104",
      name: "Shroud-White Weave, 600 Threads of Fate",
    },
    department: { code: "HSK", name: "Keepers of the Chamber" },
    account_code: { code: "1108003", name: "INVENTORY - VESTMENTS & SHROUDS" },
    is_mapped: true,
    mapping_type: "GL",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0008",
    business_unit: "BABYLON",
    store_location: { code: "4HK01", name: "Hanging Terrace Housekeeping" },
    category: { code: "3", name: "Supplies" },
    sub_category: { code: "33", name: "Cleaning Chemical" },
    item_group: { code: "3307", name: "Waters of Ritual Purification" },
    department: { code: "HSK", name: "Keepers of the Chamber" },
    account_code: { code: "1108005", name: "INVENTORY - RITES OF CLEANSING" },
    is_mapped: true,
    mapping_type: "GL",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0009",
    business_unit: "AVALON",
    store_location: { code: "5EN01", name: "Forge Beneath the Mist" },
    category: { code: "4", name: "Engineering" },
    sub_category: { code: "41", name: "Spare Parts" },
    item_group: { code: "4102", name: "Iron Wrought by a Silent Order" },
    department: { code: "ENG", name: "Order of the Forge" },
    account_code: { code: "1109001", name: "INVENTORY - RELIC COMPONENTS" },
    is_mapped: false,
    mapping_type: "GL",
    last_scanned_at: null,
  },
  {
    id: "map_0010",
    business_unit: "AVALON",
    store_location: { code: "5EN01", name: "Forge Beneath the Mist" },
    category: { code: "4", name: "Engineering" },
    sub_category: { code: "44", name: "Electrical" },
    item_group: {
      code: "4409",
      name: "Caged Lightning - Handle with Reverence",
    },
    department: { code: "ENG", name: "Order of the Forge" },
    account_code: { code: "1109004", name: "INVENTORY - BOUND ELEMENTS" },
    is_mapped: true,
    mapping_type: "GL",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0011",
    business_unit: "SHANGRI",
    store_location: { code: "6SP01", name: "Pavilion of the Still Mind" },
    category: { code: "5", name: "Spa & Wellness" },
    sub_category: { code: "52", name: "Aromatics" },
    item_group: { code: "5203", name: "Incense of the Thousand-Year Vigil" },
    department: { code: "SPA", name: "Sanctum of Stillness" },
    account_code: { code: "1110002", name: "INVENTORY - OFFERINGS & INCENSE" },
    is_mapped: true,
    mapping_type: "AP",
    last_scanned_at: "2026-07-01T03:00:00Z",
  },
  {
    id: "map_0012",
    business_unit: "SHANGRI",
    store_location: { code: "6SP01", name: "Pavilion of the Still Mind" },
    category: { code: "6", name: "Printing & Stationery" },
    sub_category: { code: "61", name: "Forms" },
    item_group: { code: "6101", name: "Scrolls Yet Unwritten" },
    department: { code: "ADM", name: "Scriptorium" },
    account_code: { code: "1111001", name: "INVENTORY - THE UNWRITTEN CODEX" },
    is_mapped: false,
    mapping_type: "AP",
    last_scanned_at: null,
  },
];
