import { describe, it, expect, vi } from "vitest";
import { render, screen } from "@testing-library/react";
import { IntlProvider } from "use-intl";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import en from "@/messages/en.json";
import type { CategoryNode } from "@/types/category";
import { NODE_TYPE } from "@/types/category";
import { CategoryForm } from "./category-form";

function renderForm(
  props: Partial<React.ComponentProps<typeof CategoryForm>>,
) {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  render(
    <QueryClientProvider client={queryClient}>
      <IntlProvider locale="en" messages={en}>
        <CategoryForm
          type="category"
          mode="add"
          onSubmit={vi.fn()}
          onCancel={vi.fn()}
          {...props}
        />
      </IntlProvider>
    </QueryClientProvider>,
  );
}

describe("CategoryForm — auto-generated code field", () => {
  it("add mode: code input is disabled with the auto-generated placeholder", () => {
    renderForm({ mode: "add" });
    const codeInput = screen.getByLabelText(en.field.code);
    expect(codeInput).toBeDisabled();
    expect(codeInput).toHaveAttribute("placeholder", en.field.autoGenerated);
  });

  it("add mode: the code label shows no required asterisk", () => {
    renderForm({ mode: "add" });
    const codeLabel = screen.getByText(en.field.code);
    expect(codeLabel.textContent).not.toContain("*");
  });

  it("edit mode: code input is disabled and shows the existing code", () => {
    const selectedNode: CategoryNode = {
      id: "cat-1",
      code: "C01",
      name: "Beverage",
      type: NODE_TYPE.CATEGORY,
      is_active: true,
      cascade_deviation: true,
    };
    renderForm({ mode: "edit", selectedNode });
    const codeInput = screen.getByLabelText(en.field.code) as HTMLInputElement;
    expect(codeInput).toBeDisabled();
    expect(codeInput.value).toBe("C01");
  });
});
