import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import { useForm } from "react-hook-form";
import { IntlProvider } from "use-intl";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import en from "@/messages/en.json";
import type { ProductDetail, ProductFormValues } from "@/types/product";
import GeneralTab from "./pd-general-tab";

const BASE_DEFAULTS: ProductFormValues = {
  name: "",
  code: "",
  local_name: "",
  description: "",
  inventory_unit_id: "",
  product_item_group_id: "",
  product_status_type: "active",
  tax_profile_id: "",
  is_used_in_recipe: false,
  is_sold_directly: false,
  barcode: "",
  sku: "",
  price: 0,
  price_deviation_limit: 0,
  qty_deviation_limit: 0,
  info: [],
  locations: [],
  order_units: [],
  ingredient_units: [],
};

function Host({
  product,
  isDisabled,
  defaults = BASE_DEFAULTS,
}: {
  product?: ProductDetail;
  isDisabled: boolean;
  defaults?: ProductFormValues;
}) {
  const form = useForm<ProductFormValues>({ defaultValues: defaults });
  return <GeneralTab form={form} isDisabled={isDisabled} product={product} />;
}

function renderTab(props: React.ComponentProps<typeof Host>) {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  return render(
    <QueryClientProvider client={queryClient}>
      <IntlProvider locale="en" messages={en}>
        <Host {...props} />
      </IntlProvider>
    </QueryClientProvider>,
  );
}

describe("GeneralTab — auto-generated code field", () => {
  it("add mode: code input is disabled with the auto-generated placeholder", () => {
    renderTab({ product: undefined, isDisabled: false });
    const codeInput = screen.getByPlaceholderText(en.field.autoGenerated);
    expect(codeInput).toBeDisabled();
  });

  it("add mode: the code label shows no required asterisk", () => {
    renderTab({ product: undefined, isDisabled: false });
    const codeLabel = screen.getByText(en.field.code);
    expect(codeLabel.textContent).not.toContain("*");
  });

  it("view mode: code is shown read-only (as text, not an input)", () => {
    const product = {
      id: "p1",
      code: "P001",
      name: "Espresso",
      product_category: { id: "c1", name: "Beverage" },
      product_sub_category: { id: "s1", name: "Coffee" },
      product_item_group: { id: "ig1", name: "Beans" },
      inventory_unit: { id: "u1", name: "KG" },
    } as unknown as ProductDetail;
    renderTab({
      product,
      isDisabled: true,
      defaults: { ...BASE_DEFAULTS, code: "P001" },
    });
    expect(screen.getByText("P001")).toBeInTheDocument();
    expect(screen.queryByPlaceholderText(en.field.autoGenerated)).toBeNull();
  });
});

describe("GeneralTab — category cascade", () => {
  it("add mode: Sub Category lookup is disabled until a Category is chosen", () => {
    renderTab({ product: undefined, isDisabled: false });
    const subCategoryTrigger = screen.getByRole("button", {
      name: en.lookup.select.replace("{entity}", en.field.subCategory),
    });
    expect(subCategoryTrigger).toBeDisabled();
  });

  it("add mode: Item Group lookup is disabled until a Sub Category is chosen", () => {
    renderTab({ product: undefined, isDisabled: false });
    const itemGroupTrigger = screen.getByRole("button", {
      name: en.productManagement.product.itemGroupPlaceholder,
    });
    expect(itemGroupTrigger).toBeDisabled();
  });
});
